name: Build and Upload

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend dependencies
        working-directory: ./word-game-web
        run: npm install

      - name: Build frontend
        working-directory: ./word-game-web
        run: npm run build

      - name: Cross-compile for macOS, Linux, and Windows
        run: |
          GOOS=darwin GOARCH=arm64 go build -o word-guessing-game-mac
          GOOS=linux GOARCH=amd64 go build -o word-guessing-game-linux
          GOOS=windows GOARCH=amd64 go build -o word-guessing-game-windows.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: word-guessing-game
          path: |
            word-guessing-game-mac
            word-guessing-game-linux
            word-guessing-game-windows.exe
            wordlist.txt
