name: Build and Upload

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend dependencies and build
        run: make frontend

      - name: Cross-compile backend for macOS, Linux, and Windows
        run: make backend

      - name: Move binaries for upload
        run: |
          mkdir upload
          cp bin/word-guessing-game* upload/
          cp wordlist.txt upload/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: word-guessing-game
          path: upload/
